### ISSUE TITLE
only images allowed?

### ISSUE THREAD

**Issue by blicksem** [henrylearn2rock/jQuery-File-Upload-CFC#3]
Hello Henry,
I am using your code for uploading files in my web-application. Images are being uploaded without a problem and I have disabled the thumbnail creation (I don't need that part).
When uploading a pdf or word file, I get errors like 'variable extension is unknown' or 'coldfusion was unable to create an image from the specified source file'.

Can you telle me how I can change the cfc('s), so that every file type is uploaded without any other actions.

Thanks in advance

**Comment by henrylearn2rock** [comment]
Hi,

It'd be great if you can at lease narrow down to the line number that throws or returns that error.

Thx,
HH

**Comment by blicksem** [comment]
Hi Henry, 

The problem is that I'm only getting the following
jquery error: 

jquery.min.js:4 POST
http://127.0.0.1:8500/FileManager/uploader/server/CF/ [2] 500
(ColdFusion was unable to create an image from the specified source
file.) 

 		send
 		@
 		jquery.min.js:4

 		m.extend.ajax
 		@

		jquery.min.js:4

 		send
 		@
 		jquery.fileupload.js:906


		$.widget._onSend
 		@
 		jquery.fileupload.js:968

 		(anonymous
function)
 		@
 		jquery.ui.widget.js:127

 		data.submit
 		@

		jquery.fileupload.js:674

 		(anonymous function)
 		@

		jquery.fileupload.js:218

 		j
 		@
 		jquery.min.js:2

 		k.add
 		@

		jquery.min.js:2

 		$.widget.options.add
 		@

		jquery.fileupload.js:217

 		$.widget.options.add
 		@

		jquery.fileupload-process.js:56

 		$.Widget._trigger
 		@

		jquery.ui.widget.js:527

 		(anonymous function)
 		@

		jquery.fileupload.js:1037

 		m.extend.each
 		@
 		jquery.min.js:2


		$.widget._onAdd
 		@
 		jquery.fileupload.js:1030

 		(anonymous
function)
 		@
 		jquery.ui.widget.js:127

 		(anonymous function)
 		@

		jquery.fileupload.js:1275

 		j
 		@
 		jquery.min.js:2

 		k.add

		@
 		jquery.min.js:2

Image file (tif, gif,jpg,png) are uploaded as
expected, but uploading a txt, pdf or other miscelanious file throws an
error because it can't be converted to an image. 

Somewhere in the code
is stated that there the uploaded file needs to be saved as an image,
but I can't figure out where that decision is made. 

I have made some
minor changes in the UploadHandler.cfm, but those where only for the
thumbnail generation an for the automatic file extension recognition.
(see attachment) 

With kind regards, 

Niels Hubregtse
Blicksem
Solutions 

Henry Ho schreef op 2015-12-04 18:14: 

> Hi, 
> 
> It'd be
great if you can at lease narrow down to the line number that throws or
returns that error. 
> 
> Thx,
> HH 
> 
> --
> Reply to this email
directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/henrylearn2rock/jQuery-File-Upload-CFC/issues/3#issuecomment-162024828
[2]
http://127.0.0.1:8500/FileManager/uploader/server/CF/

**Comment by henrylearn2rock** [comment]
narrowed down to the validate() function.  Try again with latest fix.

**Comment by blicksem** [comment]
Hi Henry,

First of all, thank your for the support, the adjustment you made seems to work.
I added a few lines of code for recognizing the unknown (image)extension. In the switch case on line 437 I added :
    default:
        extensions = [ListLast(file_path,".")];
        break;

Second:
I noticed that when I upload a file multiple times, the file gets a suffix (number) and that is great and when I delete all the files, I would suspect that after deleting the physical files the first upload (with a name used before) would not get a suffix. At this moment the suffix keeps getting increased and added to the file name. (even after restarting the ColdFusion Server). I guess that this naming convention is handled by the function get_unique_filename (line 409), but again, I do not see what I should change to make it work.

Third (and last):
The project I'm working on, is a file upload too. The user can create folders in a user specific area in the upload directory. when the user selects a folder he gets to see all the files he has uploaded and the user can delete files or upload new files. (the files uploaded will be moved to a different secure server, the files that the user sees are references pulled from a database).
On line 44/45 in the UploadHandler.cfc the upload directory is defined.This directory is static, but I would like the upload directory to be a variable like: 'upload_dir' = expandPath('/fm/files/Username/customfolder1/customfolder2')
How would you suggest to accomplish that?
A work-around that I was thinking of is moving the files in the selected folder after uploading the file, but that would take more time for uploading/processing and it would be a dirty way.

(I hope that I'm not a very big 'pain in the #ss' and that what I'm writing is readable and doesn't have to many spelling errors...)

Again thanks for the support.

Niels
