### ISSUE TITLE
Uploading large file problem

### ISSUE THREAD

**Issue by blicksem** [henrylearn2rock/jQuery-File-Upload-CFC#4]
Hi Henry, 
I'm afraid I have to ask for your help one more time.
after uploading large files (over 40mb), I can see that the file is moved from the tmp directory to the upload directory, but then I'm getting a 'internal server error' message (I have attached the error messages given by the browser)

I hope you can help me again this time.

kind regards,

Niels Hubregtse

[internal server error.txt](https://github.com/henrylearn2rock/jQuery-File-Upload-CFC/files/97822/internal.server.error.txt)

**Comment by henrylearn2rock** [comment]
That error.txt is not helpful.  Please provide the actual 500 error from ColdFusion.  Either from the coldfuison's log or if you use Developer Tool in Chrome, locate the 500 error in the network tab, and look at the actual response from the server.

**Comment by blicksem** [comment]
Hi Henry,

I have attached the exception.log and the uploadhandler.cfc

The code runs without a problem when uploading small files (<40Mb), but returns an error when uploading files above 40Mb

If you wish, I can create an account for you in my application so that you can see for yourself what happens.

Thank you for helping

Niels

Ps. I'm running a Railo 4.2 server.


[exception.zip](https://github.com/henrylearn2rock/jQuery-File-Upload-CFC/files/98225/exception.zip)

**Comment by henrylearn2rock** [comment]
The exception stated "Can't cast String [] to a boolean" for UploadHandler.cfc line 774.

Committed the fix, I think it should work, since in PHP !(anArray) == CF's !arrayLen(anArray) since both yield true if the array is empty.

**Comment by blicksem** [comment]
Hi Henry,

Thanks for the fix, it worked like a charm.

Unfortunately I ran into another problem. When uploading multiple files (my test files where 50 small files (300kb - 30mb) and another set of 50 files (50kb - 1,5mb)), at random times an error occurs.

In ColdFusion the error says that an uploaded file can't be found, but gives not exception or error in the log files

In Railo I'm getting the same error, but in the log file (see attached) is an exception generated
[exception.txt](https://github.com/henrylearn2rock/jQuery-File-Upload-CFC/files/99751/exception.txt)

Every run, the message occurs on a different file and in the upload folder files are missing, but the file that was't found is present. It look to me that somewhere in the code (line 265) the function "get_file_size" is called to early (when the file is not completely written).

Could you help out one more time (sorry)

Thanks in advance.

Niels

**Comment by henrylearn2rock** [comment]
I'm sorry, I do not think I have time to debug this issue.

**Comment by blicksem** [comment]
Hi Henry,

Thanks for the heads-up, I can understand that you don't have time to debug.
Maybe if you can find a moment in the future, I would appreciate.
For now I will use another up-loader, less advanced component for uploading, .because I need a working multi-uploader that can be trusted.

Thanks again

Niels

**Comment by henrylearn2rock** [comment]
If you don't need all the fancy rotate and thumbnail generation, you can get away with just using HTML5 multiple file input, and use cffile uploadall

http://docs.lucee.org/reference/tags/file.html
